name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: CBTS-env
    env:
      GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_IP: ${{ secrets.DB_IP }}
      STORAGE_NAME: ${{ secrets.STORAGE_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
      FORGOT_PASSWORD_URL: ${{ secrets.FORGOT_PASSWORD_URL }}
      STRIPE_ID: ${{ secrets.STRIPE_ID }}
      PRICE_ID_PREMIUM: ${{ secrets.PRICE_ID_PREMIUM }}
      PRICE_ID_ENTERPRISE: ${{ secrets.PRICE_ID_ENTERPRISE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest with coverage
        run: pytest --cov=. --cov-report=term-missing
